### ISSUE TITLE
Attempted to ref invalid pointer

### ISSUE THREAD

**Issue by JohannesBeranek** [lopcode/vips-ffm#68]
```
Caused by: app.photofox.vipsffm.VipsError: attempted to ref invalid pointer
        at app.photofox.vipsffm.VipsInvoker.refGObjectToArenaScope(VipsInvoker.java:399) ~[vips-ffm-core-0.5.3.jar:?]
        at app.photofox.vipsffm.VipsInvoker.readOutputOption(VipsInvoker.java:113) ~[vips-ffm-core-0.5.3.jar:?]
        at app.photofox.vipsffm.VipsInvoker.lambda$readOutputOptions$2(VipsInvoker.java:47) ~[vips-ffm-core-0.5.3.jar:?]
        at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184) ~[?:?]
        at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:194) ~[?:?]
        at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1709) ~[?:?]
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:556) ~[?:?]
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:546) ~[?:?]
        at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151) ~[?:?]
        at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174) ~[?:?]
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:265) ~[?:?]
        at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:611) ~[?:?]
        at app.photofox.vipsffm.VipsInvoker.readOutputOptions(VipsInvoker.java:47) ~[vips-ffm-core-0.5.3.jar:?]
        at app.photofox.vipsffm.VipsInvoker.invokeOperation(VipsInvoker.java:37) ~[vips-ffm-core-0.5.3.jar:?]
        at app.photofox.vipsffm.VImage.jpegsaveBuffer(VImage.java:2984) ~[vips-ffm-core-0.5.3.jar:?]
```

on linux

**Comment by JohannesBeranek** [comment]
While looking at the operations in that chain, I found the following in VImage.iccTransform
```
        VipsOption.String outputProfileOption = VipsOption.String("output-profile", outputProfile);
```
I think this should be `output_profile` with an underline. Not sure if it's the underlying issue though.

**Comment by JohannesBeranek** [comment]
Searching for the regex
`"[^"]*-[^"]*"` in IntelliJ IDEA inside VImage yields another 25 results of probably wrong params ...

**Comment by lopcode** [comment]
Thanks for reporting - looking at the stacktrace I'm pretty sure this is because `VipsBlob` isn't actually a `VipsObject` subtype so it's not correct to reference count - I'll investigate and fix.

**Comment by lopcode** [comment]
Fixed in `0.5.5` 🙂

**Comment by JohannesBeranek** [comment]
Works. We've now deployed vips-ffm in production (linux) and already are seeing reduced times for image generation (we're generating a lot of high-res images when building customizable PDFs). Can't give you any real numbers (except for the test numbers I already posted), but it definitely feels faster.
Thanks a lot!

**Comment by lopcode** [comment]
That's awesome - thanks so much for filing issues and sticking with the library as I get it towards a 1.0 release 🎉
