### ISSUE TITLE
Unable to make loader for libvips

### ISSUE THREAD

**Issue by JohannesBeranek** [lopcode/vips-ffm#71]
Got the following exception (linux) on our prod system:
```
Caused by: java.lang.ExceptionInInitializerError: Exception java.lang.UnsatisfiedLinkError: could not make loader for libvips [in thread "some-thread"]
        at app.photofox.vipsffm.VipsLibLookup.buildSymbolLoader(VipsLibLookup.java:13) ~[vips-ffm-core-0.5.6.jar:?]
        at app.photofox.vipsffm.jextract.VipsRaw.<clinit>(VipsRaw.java:59) ~[vips-ffm-core-0.5.6.jar:?]
        at app.photofox.vipsffm.VipsHelper.init(VipsHelper.java:16) ~[vips-ffm-core-0.5.6.jar:?]
        at app.photofox.vipsffm.Vips.init(Vips.java:17) ~[vips-ffm-core-0.5.6.jar:?]
```

Interestingly it works for some things and then suddenly this exception popped up. I'll try to narrow it down, but not sure I can do much, as those "random" errors are really hard to reproduce

**Comment by JohannesBeranek** [comment]
Nevermind, seems someone broke the lib setup on our system ...

Closing this, invalid.
